USE [GD1C2019]
GO

DROP TABLE VAMONIUEL.CABINA
DROP TABLE VAMONIUEL.Puerto
DROP TABLE VAMONIUEL.RecorridoXViaje
DROP TABLE VAMONIUEL.ViajeXRecorrido
DROP TABLE VAMONIUEL.Usuario
DROP TABLE VAMONIUEL.RECORRIDO
DROP TABLE VAMONIUEL.VIAJE
DROP TABLE [VAMONIUEL].[PASAJE]
DROP TABLE VAMONIUEL.RESERVA
DROP TABLE VAMONIUEL.CRUCERO
DROP TABLE VAMONIUEL.Rol_X_Funcion
DROP TABLE VAMONIUEL.Rol_X_Usuario
DROP TABLE VAMONIUEL.Rol
DROP TABLE VAMONIUEL.Funcion
DROP TABLE VAMONIUEL.Cliente